/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    'Welcome-to-TurboDocx',
    'Dashboard',
    {
      type: 'category',
      label: 'TurboDocx Templating',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboDocx-Templating',
        },
      ],
    },
    {
      type: 'category',
      label: 'TurboSign',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboSign',
        },
      ],
    },
    {
      type: 'category',
      label: 'TurboQuote',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboQuote',
        },
      ],
    },
    {
      type: 'category',
      label: 'Pipelines',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Pipelines',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Integrations/Google-Drive',
          label: 'Google Drive',
          className: 'integration-google-drive',
        },
        {
          type: 'doc',
          id: 'Integrations/OneDrive-and-SharePoint',
          label: 'OneDrive and SharePoint',
          className: 'integration-onedrive-sharepoint',
        },
        {
          type: 'doc',
          id: 'Integrations/SalesForce',
          label: 'Salesforce',
          className: 'integration-salesforce',
        },
        {
          type: 'doc',
          id: 'Integrations/Zoom',
          label: 'Zoom',
          className: 'integration-zoom',
        },
        {
          type: 'doc',
          id: 'Integrations/Hubspot',
          label: 'Hubspot',
          className: 'integration-hubspot',
        },
        {
          type: 'doc',
          id: 'Integrations/Teams',
          label: 'Microsoft Teams',
          className: 'integration-teams',
        },
        {
          type: 'doc',
          id: 'Integrations/Fireflies',
          label: 'Fireflies AI',
          className: 'integration-fireflies',
        },
        {
          type: 'doc',
          id: 'Integrations/ConnectWise-PSA',
          label: 'ConnectWise PSA',
          className: 'integration-connectwise',
        },
        {
          type: 'category',
          label: 'Wrike',
          className: 'integration-wrike',
          link: { type: 'doc', id: 'Integrations/Wrike/index' },
          items: [{ type: 'autogenerated', dirName: 'Integrations/Wrike' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Configuration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Advanced-Configuration',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'SDKs/index',
      },
      items: [
        {
          type: 'doc',
          id: 'SDKs/agent-skills',
          label: 'Install with AI Agents',
        },
        {
          type: 'doc',
          id: 'SDKs/developer-mode',
          label: 'Developer Mode',
        },
        {
          type: 'category',
          label: 'Install & configure',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'SDKs/javascript',
              label: 'JavaScript / TypeScript',
            },
            {
              type: 'doc',
              id: 'SDKs/python',
              label: 'Python',
            },
            {
              type: 'doc',
              id: 'SDKs/php',
              label: 'PHP',
            },
            {
              type: 'doc',
              id: 'SDKs/go',
              label: 'Go',
            },
            {
              type: 'doc',
              id: 'SDKs/java',
              label: 'Java',
            },
          ],
        },
        {
          type: 'doc',
          id: 'SDKs/turbosign',
          label: 'TurboSign SDK',
        },
        {
          type: 'doc',
          id: 'SDKs/deliverable',
          label: 'Deliverable SDK',
        },
        {
          type: 'doc',
          id: 'SDKs/webhooks',
          label: 'TurboWebhooks SDK',
        },
        {
          type: 'doc',
          id: 'SDKs/quote',
          label: 'TurboQuote SDK',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      // Pull the manually-curated, grouped structure from docs/API/sidebar.js
      // (Introduction, Deliverables, Templates, Variables, Tags, Webhooks)
      // instead of letting autogenerated dump every .api.mdx flat.
      items: require('./docs/API/sidebar.js'),
    },
  ]
};



module.exports = sidebars;
