/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    'Welcome to TurboDocx',
    {
      type: 'category',
      label: 'TurboDocx Templating',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'TurboDocx Templating/API Templates',
          label: 'Template Generation API',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/How to Create a Template',
          label: 'How to Create a Template',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/How to Create a Document Template',
          label: 'How to Create a Document Template',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/How to Create a Presentation Template',
          label: 'How to Create a Presentation Template',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/How to Create a Deliverable',
          label: 'How to Create a Deliverable',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/How to Create a Knowledgebase Entry',
          label: 'How to Create a Knowledgebase Entry',
        },
        {
          type: 'category',
          label: 'Advanced Templating Engine',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'TurboDocx Templating/Advanced Templating Engine',
              label: 'Overview & Features',
            },
            {
              type: 'doc',
              id: 'TurboDocx Templating/Simple vs Advanced Variables',
              label: 'Simple vs Advanced Variables',
            },
            {
              type: 'doc',
              id: 'TurboDocx Templating/Advanced Templating Troubleshooting',
              label: 'Troubleshooting',
            },
            {
              type: 'doc',
              id: 'TurboDocx Templating/Advanced Templating cURL Example',
              label: 'Advanced Templating CURL Example',
            },
          ],
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/ai-variable-generation',
          label: 'AI Variable Generation',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/Brand Identity',
          label: 'Brand Identity',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/Office Integration',
          label: 'Office Integration',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/Working with Fonts',
          label: 'Working with Fonts',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/Template Troubleshooting',
          label: 'Template Troubleshooting',
        },
        {
          type: 'doc',
          id: 'TurboDocx Templating/Additional Information',
          label: 'Additional Information',
        },
      ],
    },
    {
      type: 'category',
      label: 'TurboSign',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboSign',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Integrations/Google Drive',
          label: 'Google Drive',
          className: 'integration-google-drive',
        },
        {
          type: 'doc',
          id: 'Integrations/OneDrive and SharePoint',
          label: 'OneDrive and SharePoint',
          className: 'integration-onedrive-sharepoint',
        },
        {
          type: 'doc',
          id: 'Integrations/SalesForce',
          label: 'Salesforce',
          className: 'integration-salesforce',
        },
        {
          type: 'doc',
          id: 'Integrations/Zapier',
          label: 'Zapier',
          className: 'integration-zapier',
        },
        {
          type: 'doc',
          id: 'Integrations/Zoom',
          label: 'Zoom',
          className: 'integration-zoom',
        },
        {
          type: 'doc',
          id: 'Integrations/Hubspot',
          label: 'Hubspot',
          className: 'integration-hubspot',
        },
        {
          type: 'doc',
          id: 'Integrations/Teams',
          label: 'Microsoft Teams',
          className: 'integration-teams',
        },
        {
          type: 'doc',
          id: 'Integrations/Fireflies',
          label: 'Fireflies AI',
          className: 'integration-fireflies',
        },
        {
          type: 'doc',
          id: 'Integrations/ConnectWise PSA',
          label: 'ConnectWise PSA',
          className: 'integration-connectwise',
        },
        {
          type: 'doc',
          id: 'Integrations/Wrike',
          label: 'Wrike',
          className: 'integration-wrike',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Configuration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Advanced Configuration',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDKs',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'SDKs/index',
      },
      items: [
        {
          type: 'category',
          label: 'TurboSign SDKs',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'SDKs/javascript',
              label: 'JavaScript / TypeScript',
            },
            {
              type: 'doc',
              id: 'SDKs/python',
              label: 'Python',
            },
            {
              type: 'doc',
              id: 'SDKs/php',
              label: 'PHP',
            },
            {
              type: 'doc',
              id: 'SDKs/go',
              label: 'Go',
            },
            {
              type: 'doc',
              id: 'SDKs/java',
              label: 'Java',
            },
          ],
        },
        {
          type: 'category',
          label: 'TurboPartner SDKs',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'SDKs/partner-javascript',
              label: 'JavaScript / TypeScript',
            },
            {
              type: 'doc',
              id: 'SDKs/partner-php',
              label: 'PHP',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'API',
        },
      ],
    },
  ]
};



module.exports = sidebars;
