/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    'Welcome to TurboDocx',
    {
      type: 'category',
      label: 'TurboDocx Templating',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboDocx Templating',
        },
      ],
    },
    {
      type: 'category',
      label: 'TurboSign',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'TurboSign',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'Integrations/Google Drive',
          label: 'Google Drive',
          className: 'integration-google-drive',
        },
        {
          type: 'doc',
          id: 'Integrations/OneDrive and SharePoint',
          label: 'OneDrive and SharePoint',
          className: 'integration-onedrive-sharepoint',
        },
        {
          type: 'doc',
          id: 'Integrations/SalesForce',
          label: 'Salesforce',
          className: 'integration-salesforce',
        },
        {
          type: 'doc',
          id: 'Integrations/Zapier',
          label: 'Zapier',
          className: 'integration-zapier',
        },
        {
          type: 'doc',
          id: 'Integrations/Zoom',
          label: 'Zoom',
          className: 'integration-zoom',
        },
        {
          type: 'doc',
          id: 'Integrations/Hubspot',
          label: 'Hubspot',
          className: 'integration-hubspot',
        },
        {
          type: 'doc',
          id: 'Integrations/Teams',
          label: 'Microsoft Teams',
          className: 'integration-teams',
        },
        {
          type: 'doc',
          id: 'Integrations/Fireflies',
          label: 'Fireflies AI',
          className: 'integration-fireflies',
        },
        {
          type: 'doc',
          id: 'Integrations/ConnectWise PSA',
          label: 'ConnectWise PSA',
          className: 'integration-connectwise',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Configuration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Advanced Configuration',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'API',
        },
      ],
    },
  ]
};



module.exports = sidebars;
