#!/bin/bash

# Configuration - Update these values
API_TOKEN="YOUR_API_TOKEN"
ORG_ID="YOUR_ORGANIZATION_ID"
BASE_URL="https://api.turbodocx.com"

# Final Step: Generate Deliverable (Both Paths Converge Here)

echo "=== Final Step: Generate Deliverable ==="

# Template ID - This would come from either Path A (upload) or Path B (browse/select)
TEMPLATE_ID="0b1099cf-d7b9-41a4-822b-51b68fd4885a"

echo "Template ID: $TEMPLATE_ID"
echo "Generating deliverable with complex variable structure..."

# Generate deliverable with complex variable payload
curl -X POST "$BASE_URL/deliverable" \
  -H "Authorization: Bearer $API_TOKEN" \
  -H "x-rapiddocx-org-id: $ORG_ID" \
  -H "User-Agent: TurboDocx API Client" \
  -H "Content-Type: application/json" \
  -d '{
    "templateId": "'$TEMPLATE_ID'",
    "name": "Employee Contract - John Smith",
    "description": "Employment contract for new senior software engineer",
    "variables": [
      {
        "mimeType": "text",
        "name": "Employee Name",
        "placeholder": "{EmployeeName}",
        "text": "John Smith",
        "allowRichTextInjection": 0,
        "autogenerated": false,
        "count": 1,
        "order": 1,
        "subvariables": [
          {
            "placeholder": "{EmployeeName.Title}",
            "text": "Senior Software Engineer"
          },
          {
            "placeholder": "{EmployeeName.StartDate}",
            "text": "January 15, 2024"
          }
        ],
        "metadata": {
          "department": "Engineering",
          "level": "Senior"
        },
        "aiPrompt": "Generate a professional job description for a senior software engineer role"
      },
      {
        "mimeType": "text",
        "name": "Company Information",
        "placeholder": "{CompanyInfo}",
        "text": "TechCorp Solutions Inc.",
        "allowRichTextInjection": 1,
        "autogenerated": false,
        "count": 1,
        "order": 2,
        "subvariables": [
          {
            "placeholder": "{CompanyInfo.Address}",
            "text": "123 Innovation Drive, Tech City, TC 12345"
          },
          {
            "placeholder": "{CompanyInfo.Phone}",
            "text": "(555) 123-4567"
          }
        ],
        "metadata": {},
        "aiPrompt": ""
      },
      {
        "mimeType": "text",
        "name": "Project Assignments",
        "placeholder": "{ProjectAssignments}",
        "text": "Multiple ongoing projects",
        "allowRichTextInjection": 0,
        "autogenerated": false,
        "count": 3,
        "order": 3,
        "subvariables": [],
        "variableStack": {
          "0": {
            "text": "Project Alpha - Backend Development",
            "subvariables": [
              {
                "placeholder": "{ProjectAssignments.Duration}",
                "text": "6 months"
              },
              {
                "placeholder": "{ProjectAssignments.Priority}",
                "text": "High"
              }
            ]
          },
          "1": {
            "text": "Project Beta - API Integration",
            "subvariables": [
              {
                "placeholder": "{ProjectAssignments.Duration}",
                "text": "3 months"
              },
              {
                "placeholder": "{ProjectAssignments.Priority}",
                "text": "Medium"
              }
            ]
          },
          "2": {
            "text": "Project Gamma - Code Review",
            "subvariables": [
              {
                "placeholder": "{ProjectAssignments.Duration}",
                "text": "Ongoing"
              },
              {
                "placeholder": "{ProjectAssignments.Priority}",
                "text": "Low"
              }
            ]
          }
        },
        "metadata": {
          "totalProjects": 3,
          "estimatedHours": 1200
        },
        "aiPrompt": "Create detailed project descriptions for software development initiatives"
      },
      {
        "mimeType": "text",
        "name": "Benefits Package",
        "placeholder": "{BenefitsPackage}",
        "text": "Comprehensive benefits including health, dental, vision, and 401k",
        "allowRichTextInjection": 1,
        "autogenerated": false,
        "count": 1,
        "order": 4,
        "subvariables": [
          {
            "placeholder": "{BenefitsPackage.HealthInsurance}",
            "text": "Full coverage health insurance with $500 deductible"
          },
          {
            "placeholder": "{BenefitsPackage.PTO}",
            "text": "25 days paid time off annually"
          },
          {
            "placeholder": "{BenefitsPackage.Retirement}",
            "text": "401k with 6% company match"
          }
        ],
        "metadata": {
          "packageValue": "$15,000 annually",
          "effective": "First day of employment"
        },
        "aiPrompt": "Outline a competitive benefits package for a senior software engineer"
      }
    ],
    "tags": ["hr", "contract", "employee", "engineering"],
    "fonts": "[{\"name\":\"Arial\",\"usage\":269}]",
    "defaultFont": "Arial",
    "replaceFonts": true,
    "metadata": {
      "sessions": [
        {
          "id": "cf1cd4b9-6fdc-47e3-b59d-594cd6564501",
          "starttime": "2024-01-15T14:12:10.721Z",
          "endtime": "2024-01-15T14:13:45.724Z"
        }
      ],
      "createdBy": "HR Department",
      "documentType": "Employment Contract",
      "version": "v1.0"
    }
  }' | jq '.'

echo -e "\n=== Deliverable Generation Complete ==="

# Example: Simple variable structure (minimal example)
echo -e "\n--- Alternative: Simple Variable Structure ---"
echo "For a simpler example with basic variables:"

cat << 'EOF'
curl -X POST "$BASE_URL/deliverable" \
  -H "Authorization: Bearer $API_TOKEN" \
  -H "x-rapiddocx-org-id: $ORG_ID" \
  -H "User-Agent: TurboDocx API Client" \
  -H "Content-Type: application/json" \
  -d '{
    "templateId": "TEMPLATE_ID",
    "name": "Simple Document",
    "description": "Basic document generation",
    "variables": [
      {
        "mimeType": "text",
        "name": "Company Name",
        "placeholder": "{CompanyName}",
        "text": "Acme Corporation",
        "allowRichTextInjection": 0,
        "autogenerated": false,
        "count": 1,
        "order": 1,
        "subvariables": [],
        "metadata": {},
        "aiPrompt": ""
      },
      {
        "mimeType": "text",
        "name": "Date",
        "placeholder": "{Date}",
        "text": "January 15, 2024",
        "allowRichTextInjection": 0,
        "autogenerated": false,
        "count": 1,
        "order": 2,
        "subvariables": [],
        "metadata": {},
        "aiPrompt": ""
      }
    ],
    "tags": ["simple", "test"],
    "fonts": "[]",
    "defaultFont": "Arial",
    "replaceFonts": true,
    "metadata": {
      "sessions": [
        {
          "id": "simple-session-123",
          "starttime": "'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'",
          "endtime": "'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'"
        }
      ]
    }
  }'
EOF