package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"
)

// Configuration - Update these values
const (
	API_TOKEN = "YOUR_API_TOKEN"
	ORG_ID    = "YOUR_ORGANIZATION_ID"
	BASE_URL  = "https://api.turbodocx.com"
)

// DeliverableRequest represents the request structure for deliverable generation
type DeliverableRequest struct {
	TemplateID   string     `json:"templateId"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	Variables    []Variable `json:"variables"`
	Tags         []string   `json:"tags"`
	Fonts        string     `json:"fonts"`
	DefaultFont  string     `json:"defaultFont"`
	ReplaceFonts bool       `json:"replaceFonts"`
	Metadata     Metadata   `json:"metadata"`
}

type Variable struct {
	MimeType               string        `json:"mimeType"`
	Name                   string        `json:"name"`
	Placeholder            string        `json:"placeholder"`
	Text                   string        `json:"text"`
	AllowRichTextInjection int           `json:"allowRichTextInjection"`
	Autogenerated          bool          `json:"autogenerated"`
	Count                  int           `json:"count"`
	Order                  int           `json:"order"`
	Subvariables           []Subvariable `json:"subvariables"`
	VariableMetadata       VariableMetadata `json:"metadata"`
	AIPrompt               string        `json:"aiPrompt"`
}

type Subvariable struct {
	Placeholder string `json:"placeholder"`
	Text        string `json:"text"`
}

type VariableMetadata struct {
	Department string `json:"department"`
	Level      string `json:"level"`
}

type Metadata struct {
	Sessions     []Session `json:"sessions"`
	CreatedBy    string    `json:"createdBy"`
	DocumentType string    `json:"documentType"`
	Version      string    `json:"version"`
}

type Session struct {
	ID        string `json:"id"`
	StartTime string `json:"starttime"`
	EndTime   string `json:"endtime"`
}

// DeliverableResponse represents the API response structure
type DeliverableResponse struct {
	Data struct {
		Results struct {
			Deliverable struct {
				ID         string `json:"id"`
				Name       string `json:"name"`
				CreatedBy  string `json:"createdBy"`
				CreatedOn  string `json:"createdOn"`
				TemplateID string `json:"templateId"`
			} `json:"deliverable"`
		} `json:"results"`
	} `json:"data"`
}

/**
 * Final Step: Generate Deliverable (Both Paths Converge Here)
 */
func main() {
	fmt.Println("=== Final Step: Generate Deliverable ===")

	// This would come from either Path A (upload) or Path B (browse/select)
	templateID := "0b1099cf-d7b9-41a4-822b-51b68fd4885a"

	deliverableData := createDeliverableData(templateID)
	deliverable, err := generateDeliverable(deliverableData)
	if err != nil {
		fmt.Printf("Deliverable generation failed: %v\n", err)
		return
	}

	// Download the generated file
	fmt.Println("\n=== Download Generated File ===")
	err = downloadDeliverable(deliverable.Data.Results.Deliverable.ID,
		deliverable.Data.Results.Deliverable.Name+".docx")
	if err != nil {
		fmt.Printf("Download failed: %v\n", err)
		return
	}
}

/**
 * Generate a deliverable document from template with variable substitution
 */
func generateDeliverable(deliverableData DeliverableRequest) (*DeliverableResponse, error) {
	fmt.Println("Generating deliverable...")
	fmt.Printf("Template ID: %s\n", deliverableData.TemplateID)
	fmt.Printf("Deliverable Name: %s\n", deliverableData.Name)
	fmt.Printf("Variables: %d\n", len(deliverableData.Variables))

	// Convert to JSON
	jsonData, err := json.Marshal(deliverableData)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal JSON: %v", err)
	}

	// Create request
	req, err := http.NewRequest("POST", BASE_URL+"/deliverable", bytes.NewBuffer(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	// Set headers
	req.Header.Set("Authorization", "Bearer "+API_TOKEN)
	req.Header.Set("x-rapiddocx-org-id", ORG_ID)
	req.Header.Set("User-Agent", "TurboDocx API Client")
	req.Header.Set("Content-Type", "application/json")

	// Make request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to make request: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(body))
	}

	// Parse response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	var result DeliverableResponse
	err = json.Unmarshal(body, &result)
	if err != nil {
		return nil, fmt.Errorf("failed to parse JSON: %v", err)
	}

	deliverable := result.Data.Results.Deliverable
	fmt.Println("✅ Deliverable generated successfully!")
	fmt.Printf("Deliverable ID: %s\n", deliverable.ID)
	fmt.Printf("Created by: %s\n", deliverable.CreatedBy)
	fmt.Printf("Created on: %s\n", deliverable.CreatedOn)
	fmt.Printf("Template ID: %s\n", deliverable.TemplateID)

	return &result, nil
}

/**
 * Download the generated deliverable file
 */
func downloadDeliverable(deliverableID, filename string) error {
	fmt.Printf("Downloading file: %s\n", filename)

	requestURL := fmt.Sprintf("%s/deliverable/file/%s", BASE_URL, deliverableID)

	req, err := http.NewRequest("GET", requestURL, nil)
	if err != nil {
		return fmt.Errorf("failed to create request: %v", err)
	}

	req.Header.Set("Authorization", "Bearer "+API_TOKEN)
	req.Header.Set("x-rapiddocx-org-id", ORG_ID)
	req.Header.Set("User-Agent", "TurboDocx API Client")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to make request: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("download failed: %d", resp.StatusCode)
	}

	fmt.Printf("✅ File ready for download: %s\n", filename)

	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = "N/A"
	}

	contentLength := resp.Header.Get("Content-Length")
	if contentLength == "" {
		contentLength = "N/A"
	}

	fmt.Printf("📁 Content-Type: %s\n", contentType)
	fmt.Printf("📊 Content-Length: %s bytes\n", contentLength)

	// In a real application, you would save the file
	// body, err := io.ReadAll(resp.Body)
	// if err != nil {
	//     return fmt.Errorf("failed to read file content: %v", err)
	// }
	// err = os.WriteFile(filename, body, 0644)
	// if err != nil {
	//     return fmt.Errorf("failed to save file: %v", err)
	// }

	return nil
}

/**
 * Create example deliverable data with complex variables
 */
func createDeliverableData(templateID string) DeliverableRequest {
	now := time.Now().UTC().Format(time.RFC3339)

	return DeliverableRequest{
		TemplateID:  templateID,
		Name:        "Employee Contract - John Smith",
		Description: "Employment contract for new senior software engineer",
		Variables: []Variable{
			{
				MimeType:               "text",
				Name:                   "Employee Name",
				Placeholder:            "{EmployeeName}",
				Text:                   "John Smith",
				AllowRichTextInjection: 0,
				Autogenerated:          false,
				Count:                  1,
				Order:                  1,
				Subvariables: []Subvariable{
					{
						Placeholder: "{EmployeeName.Title}",
						Text:        "Senior Software Engineer",
					},
					{
						Placeholder: "{EmployeeName.StartDate}",
						Text:        "January 15, 2024",
					},
				},
				VariableMetadata: VariableMetadata{
					Department: "Engineering",
					Level:      "Senior",
				},
				AIPrompt: "Generate a professional job description for a senior software engineer role",
			},
			{
				MimeType:               "text",
				Name:                   "Company Information",
				Placeholder:            "{CompanyInfo}",
				Text:                   "TechCorp Solutions Inc.",
				AllowRichTextInjection: 1,
				Autogenerated:          false,
				Count:                  1,
				Order:                  2,
				Subvariables: []Subvariable{
					{
						Placeholder: "{CompanyInfo.Address}",
						Text:        "123 Innovation Drive, Tech City, TC 12345",
					},
					{
						Placeholder: "{CompanyInfo.Phone}",
						Text:        "(555) 123-4567",
					},
				},
				VariableMetadata: VariableMetadata{},
				AIPrompt:         "",
			},
		},
		Tags:         []string{"hr", "contract", "employee", "engineering"},
		Fonts:        `[{"name":"Arial","usage":269}]`,
		DefaultFont:  "Arial",
		ReplaceFonts: true,
		Metadata: Metadata{
			Sessions: []Session{
				{
					ID:        fmt.Sprintf("go-session-%d", time.Now().Unix()),
					StartTime: now,
					EndTime:   now,
				},
			},
			CreatedBy:    "HR Department",
			DocumentType: "Employment Contract",
			Version:      "v1.0",
		},
	}
}