# Configuration - Update these values
$API_TOKEN = "YOUR_API_TOKEN"
$ORG_ID = "YOUR_ORGANIZATION_ID"
$BASE_URL = "https://api.turbodocx.com"

##
# Final Step: Generate Deliverable (Both Paths Converge Here)
##

function Generate-Deliverable {
    param(
        [Parameter(Mandatory=$true)]
        [string]$TemplateId,
        [Parameter(Mandatory=$true)]
        [hashtable]$DeliverableData
    )

    $uri = "$BASE_URL/deliverable"

    Write-Host "Generating deliverable..."
    Write-Host "Template ID: $TemplateId"
    Write-Host "Deliverable Name: $($DeliverableData.name)"
    Write-Host "Variables: $($DeliverableData.variables.Count)"

    try {
        # Create headers
        $headers = @{
            'Authorization' = "Bearer $API_TOKEN"
            'x-rapiddocx-org-id' = $ORG_ID
            'User-Agent' = 'TurboDocx API Client'
            'Content-Type' = 'application/json'
        }

        # Convert to JSON
        $jsonBody = $DeliverableData | ConvertTo-Json -Depth 10

        # Make request
        $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $jsonBody

        # Parse JSON response
        $deliverable = $response.data.results.deliverable

        Write-Host "✅ Deliverable generated successfully!" -ForegroundColor Green
        Write-Host "Deliverable ID: $($deliverable.id)"
        Write-Host "Created by: $($deliverable.createdBy)"
        Write-Host "Created on: $($deliverable.createdOn)"
        Write-Host "Template ID: $($deliverable.templateId)"

        return $deliverable
    }
    catch {
        Write-Error "Deliverable generation failed: $($_.Exception.Message)"
        throw
    }
}

function Download-Deliverable {
    param(
        [Parameter(Mandatory=$true)]
        [string]$DeliverableId,
        [Parameter(Mandatory=$true)]
        [string]$Filename
    )

    Write-Host "Downloading file: $Filename"

    $uri = "$BASE_URL/deliverable/file/$DeliverableId"

    try {
        # Create headers
        $headers = @{
            'Authorization' = "Bearer $API_TOKEN"
            'x-rapiddocx-org-id' = $ORG_ID
            'User-Agent' = 'TurboDocx API Client'
        }

        # Make request
        $response = Invoke-WebRequest -Uri $uri -Method Get -Headers $headers

        if ($response.StatusCode -ne 200) {
            throw "Download failed: $($response.StatusCode)"
        }

        Write-Host "✅ File ready for download: $Filename" -ForegroundColor Green

        $contentType = if ($response.Headers['Content-Type']) { $response.Headers['Content-Type'] } else { 'N/A' }
        $contentLength = if ($response.Headers['Content-Length']) { $response.Headers['Content-Length'] } else { 'N/A' }

        Write-Host "📁 Content-Type: $contentType"
        Write-Host "📊 Content-Length: $contentLength bytes"

        # In a real application, you would save the file
        # [System.IO.File]::WriteAllBytes($Filename, $response.Content)

        return @{
            'filename' = $Filename
            'content_type' = $contentType
            'content_length' = $contentLength
        }
    }
    catch {
        Write-Error "Download failed: $($_.Exception.Message)"
        throw
    }
}

function New-ComplexVariables {
    return @(
        @{
            'mimeType' = 'text'
            'name' = 'Employee Name'
            'placeholder' = '{EmployeeName}'
            'text' = 'John Smith'
            'allowRichTextInjection' = 0
            'autogenerated' = $false
            'count' = 1
            'order' = 1
            'subvariables' = @(
                @{
                    'placeholder' = '{EmployeeName.Title}'
                    'text' = 'Senior Software Engineer'
                },
                @{
                    'placeholder' = '{EmployeeName.StartDate}'
                    'text' = 'January 15, 2024'
                }
            )
            'metadata' = @{
                'department' = 'Engineering'
                'level' = 'Senior'
            }
            'aiPrompt' = 'Generate a professional job description for a senior software engineer role'
        },
        @{
            'mimeType' = 'text'
            'name' = 'Company Information'
            'placeholder' = '{CompanyInfo}'
            'text' = 'TechCorp Solutions Inc.'
            'allowRichTextInjection' = 1
            'autogenerated' = $false
            'count' = 1
            'order' = 2
            'subvariables' = @(
                @{
                    'placeholder' = '{CompanyInfo.Address}'
                    'text' = '123 Innovation Drive, Tech City, TC 12345'
                },
                @{
                    'placeholder' = '{CompanyInfo.Phone}'
                    'text' = '(555) 123-4567'
                }
            )
            'metadata' = @{}
            'aiPrompt' = ''
        },
        @{
            'mimeType' = 'text'
            'name' = 'Project Assignments'
            'placeholder' = '{ProjectAssignments}'
            'text' = 'Multiple ongoing projects'
            'allowRichTextInjection' = 0
            'autogenerated' = $false
            'count' = 3
            'order' = 3
            'subvariables' = @()
            'variableStack' = @{
                '0' = @{
                    'text' = 'Project Alpha - Backend Development'
                    'subvariables' = @(
                        @{
                            'placeholder' = '{ProjectAssignments.Duration}'
                            'text' = '6 months'
                        },
                        @{
                            'placeholder' = '{ProjectAssignments.Priority}'
                            'text' = 'High'
                        }
                    )
                }
                '1' = @{
                    'text' = 'Project Beta - API Integration'
                    'subvariables' = @(
                        @{
                            'placeholder' = '{ProjectAssignments.Duration}'
                            'text' = '3 months'
                        },
                        @{
                            'placeholder' = '{ProjectAssignments.Priority}'
                            'text' = 'Medium'
                        }
                    )
                }
                '2' = @{
                    'text' = 'Project Gamma - Code Review'
                    'subvariables' = @(
                        @{
                            'placeholder' = '{ProjectAssignments.Duration}'
                            'text' = 'Ongoing'
                        },
                        @{
                            'placeholder' = '{ProjectAssignments.Priority}'
                            'text' = 'Low'
                        }
                    )
                }
            }
            'metadata' = @{
                'totalProjects' = 3
                'estimatedHours' = 1200
            }
            'aiPrompt' = 'Create detailed project descriptions for software development initiatives'
        },
        @{
            'mimeType' = 'text'
            'name' = 'Benefits Package'
            'placeholder' = '{BenefitsPackage}'
            'text' = 'Comprehensive benefits including health, dental, vision, and 401k'
            'allowRichTextInjection' = 1
            'autogenerated' = $false
            'count' = 1
            'order' = 4
            'subvariables' = @(
                @{
                    'placeholder' = '{BenefitsPackage.HealthInsurance}'
                    'text' = 'Full coverage health insurance with $500 deductible'
                },
                @{
                    'placeholder' = '{BenefitsPackage.PTO}'
                    'text' = '25 days paid time off annually'
                },
                @{
                    'placeholder' = '{BenefitsPackage.Retirement}'
                    'text' = '401k with 6% company match'
                }
            )
            'metadata' = @{
                'packageValue' = '$15,000 annually'
                'effective' = 'First day of employment'
            }
            'aiPrompt' = 'Outline a competitive benefits package for a senior software engineer'
        }
    )
}

function New-DeliverableData {
    param(
        [Parameter(Mandatory=$true)]
        [string]$TemplateId
    )

    $now = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

    return @{
        'templateId' = $TemplateId
        'name' = 'Employee Contract - John Smith'
        'description' = 'Employment contract for new senior software engineer'
        'variables' = New-ComplexVariables
        'tags' = @('hr', 'contract', 'employee', 'engineering')
        'fonts' = '[{"name":"Arial","usage":269}]'
        'defaultFont' = 'Arial'
        'replaceFonts' = $true
        'metadata' = @{
            'sessions' = @(
                @{
                    'id' = [System.Guid]::NewGuid().ToString()
                    'starttime' = $now
                    'endtime' = $now
                }
            )
            'createdBy' = 'HR Department'
            'documentType' = 'Employment Contract'
            'version' = 'v1.0'
        }
    }
}

# Example usage
try {
    Write-Host "=== Final Step: Generate Deliverable ===" -ForegroundColor Cyan

    # This would come from either Path A (upload) or Path B (browse/select)
    $templateId = "0b1099cf-d7b9-41a4-822b-51b68fd4885a"

    $deliverableData = New-DeliverableData -TemplateId $templateId
    $deliverable = Generate-Deliverable -TemplateId $templateId -DeliverableData $deliverableData

    # Download the generated file
    Write-Host "`n=== Download Generated File ===" -ForegroundColor Cyan
    $downloadResult = Download-Deliverable -DeliverableId $deliverable.id -Filename "$($deliverable.name).docx"

    Write-Host "`nGeneration and download completed successfully!" -ForegroundColor Green
}
catch {
    Write-Error "Deliverable generation failed: $($_.Exception.Message)"
    exit 1
}