require 'net/http'
require 'uri'
require 'json'
require 'securerandom'
require 'time'

# Configuration - Update these values
API_TOKEN = "YOUR_API_TOKEN"
ORG_ID = "YOUR_ORGANIZATION_ID"
BASE_URL = "https://api.turbodocx.com"

##
# Final Step: Generate Deliverable (Both Paths Converge Here)
##

def generate_deliverable(template_id, deliverable_data)
  uri = URI("#{BASE_URL}/deliverable")

  puts "Generating deliverable..."
  puts "Template ID: #{template_id}"
  puts "Deliverable Name: #{deliverable_data['name']}"
  puts "Variables: #{deliverable_data['variables'].length}"

  # Create HTTP connection
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true

  # Create request
  request = Net::HTTP::Post.new(uri)
  request['Authorization'] = "Bearer #{API_TOKEN}"
  request['x-rapiddocx-org-id'] = ORG_ID
  request['User-Agent'] = 'TurboDocx API Client'
  request['Content-Type'] = 'application/json'

  # Set request body
  request.body = deliverable_data.to_json

  # Make request
  response = http.request(request)

  unless response.code == '200'
    raise "HTTP error #{response.code}: #{response.body}"
  end

  # Parse JSON response
  result = JSON.parse(response.body)
  deliverable = result['data']['results']['deliverable']

  puts "✅ Deliverable generated successfully!"
  puts "Deliverable ID: #{deliverable['id']}"
  puts "Created by: #{deliverable['createdBy']}"
  puts "Created on: #{deliverable['createdOn']}"
  puts "Template ID: #{deliverable['templateId']}"

  deliverable
rescue JSON::ParserError => e
  raise "Failed to parse JSON response: #{e.message}"
rescue => e
  puts "Deliverable generation failed: #{e.message}"
  raise
end

def download_deliverable(deliverable_id, filename)
  puts "Downloading file: #{filename}"

  uri = URI("#{BASE_URL}/deliverable/file/#{deliverable_id}")

  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true

  request = Net::HTTP::Get.new(uri)
  request['Authorization'] = "Bearer #{API_TOKEN}"
  request['x-rapiddocx-org-id'] = ORG_ID
  request['User-Agent'] = 'TurboDocx API Client'

  response = http.request(request)

  unless response.code == '200'
    raise "Download failed: #{response.code}"
  end

  puts "✅ File ready for download: #{filename}"

  content_type = response['Content-Type'] || 'N/A'
  content_length = response['Content-Length'] || 'N/A'

  puts "📁 Content-Type: #{content_type}"
  puts "📊 Content-Length: #{content_length} bytes"

  # In a real application, you would save the file
  # File.write(filename, response.body)

  {
    'filename' => filename,
    'content_type' => content_type,
    'content_length' => content_length
  }
rescue => e
  puts "Download failed: #{e.message}"
  raise
end

def create_complex_variables
  [
    {
      'mimeType' => 'text',
      'name' => 'Employee Name',
      'placeholder' => '{EmployeeName}',
      'text' => 'John Smith',
      'allowRichTextInjection' => 0,
      'autogenerated' => false,
      'count' => 1,
      'order' => 1,
      'subvariables' => [
        {
          'placeholder' => '{EmployeeName.Title}',
          'text' => 'Senior Software Engineer'
        },
        {
          'placeholder' => '{EmployeeName.StartDate}',
          'text' => 'January 15, 2024'
        }
      ],
      'metadata' => {
        'department' => 'Engineering',
        'level' => 'Senior'
      },
      'aiPrompt' => 'Generate a professional job description for a senior software engineer role'
    },
    {
      'mimeType' => 'text',
      'name' => 'Company Information',
      'placeholder' => '{CompanyInfo}',
      'text' => 'TechCorp Solutions Inc.',
      'allowRichTextInjection' => 1,
      'autogenerated' => false,
      'count' => 1,
      'order' => 2,
      'subvariables' => [
        {
          'placeholder' => '{CompanyInfo.Address}',
          'text' => '123 Innovation Drive, Tech City, TC 12345'
        },
        {
          'placeholder' => '{CompanyInfo.Phone}',
          'text' => '(555) 123-4567'
        }
      ],
      'metadata' => {},
      'aiPrompt' => ''
    },
    {
      'mimeType' => 'text',
      'name' => 'Project Assignments',
      'placeholder' => '{ProjectAssignments}',
      'text' => 'Multiple ongoing projects',
      'allowRichTextInjection' => 0,
      'autogenerated' => false,
      'count' => 3,
      'order' => 3,
      'subvariables' => [],
      'variableStack' => {
        '0' => {
          'text' => 'Project Alpha - Backend Development',
          'subvariables' => [
            {
              'placeholder' => '{ProjectAssignments.Duration}',
              'text' => '6 months'
            },
            {
              'placeholder' => '{ProjectAssignments.Priority}',
              'text' => 'High'
            }
          ]
        },
        '1' => {
          'text' => 'Project Beta - API Integration',
          'subvariables' => [
            {
              'placeholder' => '{ProjectAssignments.Duration}',
              'text' => '3 months'
            },
            {
              'placeholder' => '{ProjectAssignments.Priority}',
              'text' => 'Medium'
            }
          ]
        },
        '2' => {
          'text' => 'Project Gamma - Code Review',
          'subvariables' => [
            {
              'placeholder' => '{ProjectAssignments.Duration}',
              'text' => 'Ongoing'
            },
            {
              'placeholder' => '{ProjectAssignments.Priority}',
              'text' => 'Low'
            }
          ]
        }
      },
      'metadata' => {
        'totalProjects' => 3,
        'estimatedHours' => 1200
      },
      'aiPrompt' => 'Create detailed project descriptions for software development initiatives'
    },
    {
      'mimeType' => 'text',
      'name' => 'Benefits Package',
      'placeholder' => '{BenefitsPackage}',
      'text' => 'Comprehensive benefits including health, dental, vision, and 401k',
      'allowRichTextInjection' => 1,
      'autogenerated' => false,
      'count' => 1,
      'order' => 4,
      'subvariables' => [
        {
          'placeholder' => '{BenefitsPackage.HealthInsurance}',
          'text' => 'Full coverage health insurance with $500 deductible'
        },
        {
          'placeholder' => '{BenefitsPackage.PTO}',
          'text' => '25 days paid time off annually'
        },
        {
          'placeholder' => '{BenefitsPackage.Retirement}',
          'text' => '401k with 6% company match'
        }
      ],
      'metadata' => {
        'packageValue' => '$15,000 annually',
        'effective' => 'First day of employment'
      },
      'aiPrompt' => 'Outline a competitive benefits package for a senior software engineer'
    }
  ]
end

def create_deliverable_data(template_id)
  now = Time.now.utc.strftime('%Y-%m-%dT%H:%M:%S.%3NZ')

  {
    'templateId' => template_id,
    'name' => 'Employee Contract - John Smith',
    'description' => 'Employment contract for new senior software engineer',
    'variables' => create_complex_variables,
    'tags' => ['hr', 'contract', 'employee', 'engineering'],
    'fonts' => '[{"name":"Arial","usage":269}]',
    'defaultFont' => 'Arial',
    'replaceFonts' => true,
    'metadata' => {
      'sessions' => [
        {
          'id' => SecureRandom.uuid,
          'starttime' => now,
          'endtime' => now
        }
      ],
      'createdBy' => 'HR Department',
      'documentType' => 'Employment Contract',
      'version' => 'v1.0'
    }
  }
end

# Example usage
begin
  puts "=== Final Step: Generate Deliverable ==="

  # This would come from either Path A (upload) or Path B (browse/select)
  template_id = "0b1099cf-d7b9-41a4-822b-51b68fd4885a"

  deliverable_data = create_deliverable_data(template_id)
  deliverable = generate_deliverable(template_id, deliverable_data)

  # Download the generated file
  puts "\n=== Download Generated File ==="
  download_deliverable(deliverable['id'], "#{deliverable['name']}.docx")

rescue => e
  puts "Deliverable generation failed: #{e.message}"
  exit 1
end